Hafte 11/HW11/CompleteProject/Controllers/LibraryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Xml.Linq;

namespace CompleteProject.Controllers
{
    public class LibraryController : Controller
    {
        private readonly DataRepo repo = new DataRepo();
        public IActionResult Index()
        {
            var model = repo.Libraries.Include(x => x.Books).Include(x => x.Members).Include(x=>x.City).ToList();
            return View(model);
        }
        public IActionResult SearchById(int? id)
        {
            if (id == null || id == 0)
                return RedirectToAction("Index");
            var model = repo.Libraries.Include(x => x.Books).Include(x => x.Members).Include(x => x.City).Where(x => x.Id == id).ToList();
            return View("Index", model);
        }
        public IActionResult SearchByName(string? name)
        {
            if (name == null)
                return RedirectToAction("Index");
            var model = repo.Libraries.Include(x => x.Books).Include(x => x.Members).Include(x => x.City).Include(x=>x.City).Where(x => x.Name.Contains(name)).ToList();
            return View("Index", model);
        }
        public IActionResult SearchByMember(string? name)
        {
            if (name == null)
                return RedirectToAction("Index");
            var model = repo.Libraries.Include(x => x.Books).Include(x => x.Members).Include(x => x.City).Where(x => x.Members.Any(y => y.FirstName.Contains(name) || y.LastName.Contains(name))).ToList();
            return View("Index", model);
        }
        public IActionResult SearchByAddress(string? name)
        {
            if (name == null)
                return RedirectToAction("Index");
            var model = repo.Libraries.Include(x => x.Books).Include(x => x.Members).Include(x => x.City).Where(x => x.Address.Contains(name)||x.City.Name.Contains(name)).ToList();
            return View("Index", model);
        }
        public IActionResult SearchByBorrowedBooks(string? name)
        {
            if (name == null)
                return RedirectToAction("Index");
            var model = repo.Libraries.Include(x => x.Books).Include(x => x.Members).Include(x => x.City).Where(x => x.Books.Any(y => y.IsBorrowed && y.Title.Contains(name))).ToList();
            return View("Index", model);
        }
    }
}

Hafte 11/HW11/CompleteProject/Controllers/MemberController.cs
using CompleteProject.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CompleteProject.Controllers
{
    public class MemberController : Controller
    {
        private readonly DataRepo repo = new DataRepo();
        public IActionResult Index()
        {
            var model = repo.Members.ToList();
            return View(model);
        }



        public IActionResult Detail(int id)
        {
            var member = repo.Members.SingleOrDefault(x => x.Id == id);
            return View(member);
        }



        public IActionResult Remove(int id)
        {
            repo.Members.Remove(repo.Members.SingleOrDefault(x => x.Id == id));
            repo.SaveChanges();
            return RedirectToAction("Index");
        }





        [HttpGet]
        public IActionResult Add()
        {
            var model = new Member();
            return View(model);
        }

        [HttpPost]
        public IActionResult Add(Member model)
        {

            repo.Members.Add(new Member
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                SSID = model.SSID,
                Mobile = model.Mobile,
                BirthDate = model.BirthDate,
                SubscriptionType = model.SubscriptionType,
                Gender = model.Gender,
            });
            repo.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var model = repo.Members.SingleOrDefault(x => x.Id == id);
            return View(model);
        }

        [HttpPost]
        public IActionResult Update(Member model, int id)
        {
            var result = repo.Members.SingleOrDefault(x => x.Id == id);
            result.FirstName = model.FirstName;
            result.LastName = model.LastName;
            result.SSID = model.SSID;
            result.Mobile = model.Mobile;
            result.BirthDate = model.BirthDate;
            result.SubscriptionType = model.SubscriptionType;
            result.Gender = model.Gender;
            repo.SaveChanges();
            return RedirectToAction("Index");
        }




        public IActionResult Search(string? name)
        {
            if (name == null)
                return RedirectToAction("Index");
            var model = repo.Members.ToList().Where(x => x.FirstName.Contains(name) || x.LastName.Contains(name)).ToList();
            return View("Index", model);
        }
    }
}

Hafte 11/HW11/CompleteProject/Controllers/TableChairController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CompleteProject.Controllers
{
    public class TableChairController : Controller
    {
        private readonly DataRepo repo = new DataRepo();

        public IActionResult Index()
        {
            var model = repo.Bills.Include(x => x.Buyer).Include(x => x.Seller).Include(x => x.Shop).Include(x => x.Manufacturers).ToList();
            return View(model);
        }
        public IActionResult BuyerDetail(int id)
        {
            var model = repo.Buyers.SingleOrDefault(x => x.Id == id);
            return View(model);
        }
        public IActionResult SellerDetail(int id)
        {
            var model = repo.Sellers.SingleOrDefault(x => x.Id == id);
            return View(model);
        }
        public IActionResult ManDetail(int id)
        {
            var model = repo.Manufacturers.Include(x => x.Bills).SingleOrDefault(x => x.Id == id);
            return View(model);
        }
        public IActionResult ShopDetail(int id)
        {
            var model = repo.Shops.SingleOrDefault(x => x.Id == id);
            return View(model);
        }
    }
}

Hafte 11/HW11/CompleteProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - WebApplication1</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Vazirmatn&display=swap" rel="stylesheet">

	<style>
		* {
			font-family: 'Vazirmatn', sans-serif;
			direction: rtl;
		}
	</style>
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">خانه</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="Index">لیست اعضا</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Library" asp-action="Index">کتابخانه‌ها</a>
						</li>						
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="TableChair" asp-action="Index">فاکتور‌ها</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2022 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>